Docker: fix Siena module installer to use framework homepage (#52)
playframework/play1#1126 was fixed long time ago,
but the provided workaround didn't notice that:

Traceback (most recent call last):
  File "/play/play", line 159, in <module>
    status = cmdloader.commands[play_command].execute(command=play_command, app=play_app, args=remaining_args, env=play_env, cmdloader=cmdloader)
  File "/play/framework/pym/play/commands/modulesrepo.py", line 61, in execute
    install(app, args, env)
  File "/play/framework/pym/play/commands/modulesrepo.py", line 448, in install
~        _            _
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/
~
~ play! 1.4.6, https://www.playframework.com
~
~ Will install siena-2.0.7
~ This module is compatible with: [1.2.3,)
~ Do you want to install this version (y/n)?     ok = raw_input('~ Do you want to install this version (y/n)? ')
EOFError: EOF when reading a line
Downloading directly ...
Archive:  siena-2.0.7.zip

Fixes: 56dd92481cb0 ("Update Dockerfile to install Siena module (#52)")