Docker: stop Supervisord (so the container) when a service enters FATAL state
Looks much better:

2022-05-01 20:06:23,786 INFO exited: openseedbox (exit status 1; not expected)
2022-05-01 20:06:26,792 INFO spawned: 'openseedbox' with pid 106
Starting play in /src/openseedbox
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
~        _            _
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/
~
~ play! 1.4.6, https://www.playframework.com
~
~ Ctrl+C to stop
~
~ using java version "11.0.14.1"
2022-05-01 20:06:26,973 INFO exited: openseedbox (exit status 1; not expected)
2022-05-01 20:06:27,974 INFO gave up: openseedbox entered FATAL state, too many start retries too quickly
2022-05-01 20:06:28,977 WARN received SIGQUIT indicating exit request
2022-05-01 20:06:28,977 INFO waiting for nginx, supervisord-stopper to die
2022-05-01 20:06:29,983 INFO stopped: nginx (exit status 0)
2022-05-01 20:06:29,985 INFO stopped: supervisord-stopper (terminated by SIGTERM)