views: use "size()" to get the size of the list (#111)
Use "size()" method call instead querying the "size" property on lists.
This surfaced when I tested Ebean as ORM instead Siena.

Exception 1:
@806koji7f
Internal Server Error (500) for request GET /admin/jobs

Template execution error (In /app/views/admin/jobs.html around line 3)
Execution error occurred in template /app/views/admin/jobs.html. Exception raised was GroovyRuntimeException : Cannot compare java.util.ArrayList with value '[]' and java.lang.Integer with value '0'.

play.exceptions.TemplateExecutionException: Cannot compare java.util.ArrayList with value '[]' and java.lang.Integer with value '0'
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:83)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:280)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:203)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:28)
	at play.mvc.Controller.renderTemplate(Controller.java:836)
	at play.mvc.Controller.renderTemplate(Controller.java:814)
	at play.mvc.Controller.render(Controller.java:876)
	at controllers.Admin.jobs(Admin.java:258)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:536)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:467)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:436)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:159)
	at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.GroovyRuntimeException: Cannot compare java.util.ArrayList with value '[]' and java.lang.Integer with value '0'
	at /app/views/admin/jobs.html.(line:3)
	at /app/views/admin/jobs.html.(line:60)
	at /app/views/admin/jobs.html.(line:58)
	at /app/views/admin/jobs.html.(line:65)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:255)
	... 13 more

Exception 2:
@806n9gok7
Internal Server Error (500) for request GET /admin/jobs

Template execution error (In /app/views/admin/jobs.html around line 3)
Execution error occurred in template /app/views/admin/jobs.html. Exception raised was MissingPropertyException : Exception evaluating property 'size' for com.avaje.ebean.common.BeanList, Reason: groovy.lang.MissingPropertyException: No such property: size for class: com.openseedbox.models.JobEvent Possible solutions: id.

play.exceptions.TemplateExecutionException: Exception evaluating property 'size' for com.avaje.ebean.common.BeanList, Reason: groovy.lang.MissingPropertyException: No such property: size for class: com.openseedbox.models.JobEvent
Possible solutions: id
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:83)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:280)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:203)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:28)
	at play.mvc.Controller.renderTemplate(Controller.java:836)
	at play.mvc.Controller.renderTemplate(Controller.java:814)
	at play.mvc.Controller.render(Controller.java:876)
	at controllers.Admin.jobs(Admin.java:258)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:536)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:467)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:436)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:159)
	at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.MissingPropertyException: Exception evaluating property 'size' for com.avaje.ebean.common.BeanList, Reason: groovy.lang.MissingPropertyException: No such property: size for class: com.openseedbox.models.JobEvent
Possible solutions: id
	at /app/views/admin/jobs.html.(line:3)
	at /app/views/admin/jobs.html.(line:60)
	at /app/views/admin/jobs.html.(line:58)
	at /app/views/admin/jobs.html.(line:65)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:255)
	... 13 more

This is because Siena uses ArrayList, but Ebean used "com.avaje.ebean.common.BeanList".
For the details, let me quote from [1]:

This is no groovy issue. It is due to difference in implementation of
ArrayList on Sun/IBM JVM. (and due to the fact that groovy allows access
to private members, but that's a known issue)
On Sun JVM, the ArrayList class has a private property called size,
that's why list.size returns you the value of that property.
On IBM JVM, the ArrayList class does not have any property called size,
in that case groovy behavior is to apply the property on each
member of the collection and collect values of all member.property
in a collection and return.
So, it now expects "size" property on each collection member, but that
also fails because String class also does not have any size property.
If you are interested in getting the size of the list then list.size is
not the groovy-way to get it anyway - it is list.size().

1: https://issues.apache.org/jira/browse/GROOVY-4094