Fix for NPE on Job status page caused by nullable |items| parameter of renderTable()
Internal Server Error (500) for request GET /admin/jobs

Template execution error (In /app/views/admin/jobs.html around line 3)
Execution error occured in template /app/views/admin/jobs.html. Exception raised was NullPointerException : Cannot get property 'size' on null object.

play.exceptions.TemplateExecutionException: Cannot get property 'size' on null object
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:272)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:202)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:661)
	at play.mvc.Controller.renderTemplate(Controller.java:641)
	at play.mvc.Controller.render(Controller.java:696)
	at controllers.Admin.jobs(Admin.java:185)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:557)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:508)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.NullPointerException: Cannot get property 'size' on null object
	at /app/views/admin/jobs.html.(line:3)
	at /app/views/admin/jobs.html.(line:48)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:247)
	... 13 more