Docker: reduce image size by specifying Java modules
List of dependant Java modules was created using the following command:

{ /java/bin/jdeps -recursive -s /play/framework/lib/*.jar & \
/java/bin/jdeps -recursive -s /src/openseedbox/lib/*.jar; } \
| awk '/java\.|jdk\./ && !/package:/ {print $3}' | sort | uniq

and resulted in 20 modules:

java.base
java.compiler
java.datatransfer
java.desktop
java.instrument
java.logging
java.management
java.management.rmi
java.naming
java.prefs
java.rmi
java.scripting
java.security.jgss
java.security.sasl
java.sql
java.transaction.xa
java.xml
jdk.jdi
jdk.management
jdk.unsupported

The project depends on two additional modules:

java.sql.rowset
jdk.crypto.cryptoki

otherwise the application startup ends in an exception:
Exception in thread "main" java.lang.NoClassDefFoundError: javax/sql/rowset/CachedRowSet

or the backend node healthcheck always fails with:
Unable to connect to backend! The administrators have been notified.